[tool.autopep8]
max_line_length = 120
aggressive = 2
recursive = true
in_place = true
select = "E, W, F"
exclude = ".venv,.git,__pycache__,build,dist,*.md,version_finder_env,pytest"
src_dirs = [
    "core/src",
    "cli/src",
    "gui/src"
]
