name: Publish Core to PyPI

on:
  push:
    tags:
      - 'gui-v*'  # Trigger when a tag starting with "gui-v" is pushed
  workflow_dispatch:


jobs:
  build-and-publish-gui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel twine

    - name: Build and publish gui
      run: |
        python -m build -s gui/
        python -m twine upload gui/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
