name: Publish Core to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger when a tag starting with "v" is pushed
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Release and Coverage"
    types:
      - completed


jobs:
  build-and-publish-core:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel twine build

    - name: Build and publish core
      run: |
        python -m build -s core/
        python -m twine upload core/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
