name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1

      - name: Upgrade npm
        run: npm install -g npm@9.5.1

      - name: Install dependencies
        id: install_dependencies
        run: npm ci
        continue-on-error: true

      - name: Print npm debug log on failure
        if: ${{ steps.install_dependencies.outcome == 'failure' }}
        run: cat /home/runner/.npm/_logs/*-debug.log

      - name: Build Linux package
        if: ${{ steps.install_dependencies.outcome == 'success' }}
        run: npm run build-linux

      - name: List build directory
        if: ${{ steps.install_dependencies.outcome == 'success' }}
        run: ls -al release-builds

      - name: Archive Linux package
        if: ${{ steps.install_dependencies.outcome == 'success' }}
        run: tar -czvf linux-package.tar.gz -C release-builds VersionFinder-linux-x64

      - name: List current directory
        if: ${{ steps.install_dependencies.outcome == 'success' }}
        run: ls -al

      - name: Upload Linux package
        if: ${{ steps.install_dependencies.outcome == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: linux-package
          path: linux-package.tar.gz

  package-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1

      - name: Upgrade npm
        run: npm install -g npm@9.5.1

      - name: Install dependencies
        id: install_dependencies
        run: npm ci
        continue-on-error: true

      - name: Print npm debug log on failure
        if: ${{ steps.install_dependencies.outcome == 'failure' }}
        run: cat /Users/runner/.npm/_logs/*-debug.log

      - name: Build macOS package
        if: ${{ steps.install_dependencies.outcome == 'success' }}
        run: npm run build-mac

      - name: List build directory
        if: ${{ steps.install_dependencies.outcome == 'success' }}
        run: ls -al release-builds

      - name: Archive macOS package
        if: ${{ steps.install_dependencies.outcome == 'success' }}
        run: tar -czvf macos-package.tar.gz -C release-builds VersionFinder-darwin-x64

      - name: List current directory
        if: ${{ steps.install_dependencies.outcome == 'success' }}
        run: ls -al

      - name: Upload macOS package
        if: ${{ steps.install_dependencies.outcome == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: macos-package
          path: macos-package.tar.gz

  publish:
    needs: [build, package-macos]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Linux package
        uses: actions/download-artifact@v2
        with:
          name: linux-package
          path: linux-package.tar.gz

      - name: Download macOS package
        uses: actions/download-artifact@v2
        with:
          name: macos-package
          path: macos-package.tar.gz

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Linux package to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux-package.tar.gz
          asset_name: linux-package.tar.gz
          asset_content_type: application/gzip

      - name: Upload macOS package to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: macos-package.tar.gz
          asset_name: macos-package.tar.gz
          asset_content_type: application/gzip
