name: Manual Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.semantic_release.outputs.released }}
      upload_url: ${{ steps.semantic_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ADMIN_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 20.14.0

      - name: Install dependencies
        id: install_dependencies
        run: npm ci
        continue-on-error: true

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
            branch: main  # Specify the branch to release from if different from the default
        env:
            GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}
            NPM_TOKEN: "Dummy value to avoid npm error"
            DEBUG: semantic-release:*
